# pqpn/pqpn_config.yaml

# Configuration for the Photonic Quantum Processor Network (PQPN)

# General Settings
general:
  network_name: "PQPN_Network"  # Name of the PQPN network
  version: "1.0"                 # Version of the PQPN implementation
  description: "A network of photonic quantum processors for advanced data processing."

# Photonic Processor Settings
photonic_processor:
  max_processors: 20              # Maximum number of photonic processors in the network
  processor_type: "PsiQuantum"    # Type of photonic processor used
  calibration_factor: 1.0          # Calibration factor for processors
  operational_mode: "Distributed"  # Operational mode (Distributed, Centralized)
  cooling_system:                  # Cooling system settings for processors
    type: "Cryogenic"              # Type of cooling system (Cryogenic, Passive, Active)
    temperature: -273               # Operating temperature in Celsius

# Data Transmission Settings
data_transmission:
  transmission_layer: "Photonic"  # Type of data transmission layer
  max_bandwidth: 10.0              # Maximum bandwidth in Gbps
  latency: 0.05                    # Expected latency in seconds
  error_correction:                 # Error correction settings
    enabled: true                   # Enable or disable error correction
    method: "Quantum"               # Method of error correction (Quantum, Classical)

# Quantum AI Settings
quantum_ai:
  enabled: true                    # Enable or disable Quantum AI features
  algorithm: "Quantum-AI-Arbitration"  # Algorithm used for Quantum AI processing
  processing_time_limit: 10        # Maximum processing time for AI tasks in seconds
  model_path: "models/quantum_ai_model.h5"  # Path to the pre-trained AI model

# Security Settings
security:
  encryption:                     # Encryption settings
    enabled: true                  # Enable or disable encryption for data transmission
    algorithm: "AES"               # Encryption algorithm to use (e.g., AES, RSA)
    key_length: 256                # Key length for encryption
  authentication:                 # Authentication settings
    enabled: true                  # Enable or disable authentication
    method: "HMAC"                 # Method for authentication (e.g., HMAC, JWT)
    secret_key: "your_secret_key"  # Secret key for HMAC authentication

# Logging Settings
logging:
  level: DEBUG                    # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: "pqpn.log"                # Log file name
  max_size: 20MB                  # Maximum size of the log file before rotation
  backup_count: 5                 # Number of backup log files to keep
  rotation:                       # Log rotation settings
    enabled: true                  # Enable log rotation
    when: "midnight"               # Rotate logs at midnight
    interval: 1                    # Rotate logs every day
