name: Auto-merge Dependabot PRs

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto-merge Dependabot PRs
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_NUMBER=$(echo $PR_URL | awk -F/ '{print $NF}')
          
          echo "Checking PR #$PR_NUMBER from Dependabot..."
          
          # Approve the PR
          gh pr review $PR_NUMBER --approve
          
          # Enable auto-merge
          gh pr merge $PR_NUMBER --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}